#!/bin/sh
sed -e 's/()/EMPTY_LIST/g' \
    -e 's/(/list(/g' -e 's/)/,0)/g' \
    -e 's/ /,/g' \
    -e 's/?//g' \
    -e 's/!//g' \
    -e 's/->/2/g' \
    -e 's/#f/HASH_F/g' \
    -e 's/#t/HASH_T/g'
